// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lubwxsdgfvzpaojowgau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1Ynd4c2RnZnZ6cGFvam93Z2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDY3NTgsImV4cCI6MjA3MDkyMjc1OH0.9fqI3pVrue_tZvnFkyhcQWPTjQrHXgk3VF-XeLFOjqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});